### PR TITLE
BEP-151: Decommission Decentralized Exchange on BNB Beacon Chain

### PR DESCRIPTION
**Pull request by owen-reorg**
# BEP-151: Decommission Decentralized Exchange on BNB Beacon Chain

## 1. Summary
This BEP proposes to securely and smoothly decommission the build-in decentralized exchange on BNB Beacon Chain.

## 2. Abstract
BNB Beacon Chain’s primary focus, its native decentralized application ("dApp") BNB DEX, has demonstrated its low-latency matching with large capacity headroom. With the development of BNB Smart Chain and AMM-based decentralized exchanges running well on it, BNB DEX has less usage and liquidity. After implementing this BEP, the DEX module will be disabled, which will give Beacon Chain more computing power for the future computing and governance focuses.

## 3. Status
Draft

## 4. Motivation
BNB Beacon Chain(BC) is a blockchain developed by the BNB Chain community that implements a vision of a decentralized exchange (DEX) for digital assets. The heart of Beacon Chain is a highly performant matching engine built on distributed consensus that aims to replicate the < 1 second trading efficiency of current centralized exchanges.

Since BNB Smart Chain's(BSC) launch to mainnet in 2020, the AMM based decentralized exchanges gain great success on BSC which even steal the thunder of order-book based DEX on BC. BC and BSC is a dual chain structure, with the evolution of this structure, BC plays more like a Beacon Chain that helps to enhance the security of BSC as a staking and governance layer. It is not suitable for a Beacon Chain to sustain a high-performance DEX any longer, especially when there is another DEX with massive adoption in the same ecosystem.

Decommissioning the DEX module will reduce the need for system resources significantly for both validators and full nodes. The demand for liquidation can be fulfilled by BNB Smart Chain or the upcoming zkBAS.

## 5. Specification
After the implementation of this BEP, transactions related to DEX(including `NewOrderMsg`, `ListMsg`, `ListMiniMsg`) will return an error to disable listing new trading pairs or placing any new orders.
All the existing orders will be canceled either by traders or by 3 days timeout(or 30 days for orders in the best 500 price levels, according to [BEP-67](https://github.com/bnb-chain/BEPs/blob/master/BEP67.md)). Thus there will be no more DEX transactions on Beacon Chain.

### 5.1 Safety
After the implementation of this BEP, there will be no more new orders.
The existing orders which are not matched yet will not be matched anymore.
They can be canceled by the traders directly or by timeout automatically after a period of time, and refunded to the traders.
All the funds are SAFU.

### 5.2 Impact
Transactions `MsgSubmitProposal` with type of `ProposalTypeListTradingPair` or `ProposalTypeDelistTradingPair` are used for submitting proposals to list new trading pairs or delist trading pairs.

They might be not useful any longer but still valid after the BEP. It's not encouraged to send these transactions anymore.

## 6. License
The content is licensed under [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

### CODE REVIEW

**Comment by que1414** [comment]
M

**Review by guagualvcha — APPROVED** [review]

**Review by guagualvcha — APPROVED** [review]

**Review by JurbinM — APPROVED** [review]
2.9

**Comment by Bladez1753** [comment]
owen-reorg:bc-dex-prune

**Comment by Arielek9** [comment]
Wtf

**Comment by blaaauw** [comment]
Noted

**Pull request merged**
